### ISSUE TITLE
Glyphicons font not loading in Rails 4.0 app

### ISSUE THREAD

**Issue by andrewhavens** [twbs/bootstrap-sass#961]
Following the advice found in many of these issues, I am unable to solve the problem of the missing Glyphicons font.

Our project is open-source ([repo](https://github.com/ruby-rcade/RubyGameDev.com)) and can be seen online ([website](https://www.rubygamedev.com)).

Relevant gems:
* rails (4.0.13)
* bootstrap-sass (3.3.4.1)
* sass-rails (5.0.3)
* sass (3.4.18)
* sprockets-rails (2.3.2)

In our `application.css.scss`:

```
@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootstrap/theme";
// ...
```

What am I missing? What versions work?

**Comment by AndrewVos** [comment]
Getting the same issue here.

**Comment by ivanbozic** [comment]
Same issue here on several projects.

Here is an example of the gem versions on a specific project.

* rails (4.1.6)
* bootstrap-sass (3.3.5)
* sass-rails (4.0.5)
* sass (3.2.19)
* sprockets-rails (2.3.2)

**Comment by sethk** [comment]
Looks like the @at-root directive requires Sass 3.3, as per the release notes here: http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#_at-root

**Comment by sethk** [comment]
This was fixed in bf9b497538b8c74e9cb29ba8a754184ebee499dd, which is 1 commit ahead of 3.3.5. Here's a workaround:

```
gem 'bootstrap-sass', github: 'twbs/bootstrap-sass', ref: 'bf9b497538b8c74e9cb29ba8a754184ebee499dd'
```

**Comment by glebm** [comment]
Ah. It is best to just specify the Sass dependency explicitly:

```ruby
gem 'sass', '~> 3.3'
```

**Comment by AndrewVos** [comment]
With these workarounds `glyphicons-option-vertical` still doesn't work. `glyphicons-search` does, though, which is weird.

**Comment by danielross** [comment]
Removing `bootstrap-sprockets` and adding `$icon-font-path: "/assets/bootstrap/";` instead, fixed it for me.

`bootstrap-sprockets` was adding absolute paths when I needed relative paths instead.

**Comment by sethk** [comment]
@glebm Unfortunately that wasn't possible because bootstrap-sass 3.3.5 is dependent upon ~> 3.2.

**Comment by glebm** [comment]
@sethk `~> 3.2` just means `>= 3.2.0`, `< 4.0`. I would be very surprised if it doesn't work. Have you tried?

**Comment by sethk** [comment]
Oops, looks like I actually wasn't limited to sass-3.2 by this gem, but by sass-rails:

```
Bundler could not find compatible versions for gem "sass":
  In Gemfile:
    sass-rails (~> 4.0.3) ruby depends on
      sass (~> 3.2.2) ruby

    sass (>= 3.2.19) ruby

    sass (>= 3.3) ruby
```

I was confused by some test Gemfiles in bf9b497538b8c74e9cb29ba8a754184ebee499dd that depended on sass ~> 3.2.

**Comment by dmexs** [comment]
Upgraded to sass 3.3 and still not having luck with getting the icons to show up . I'm using rails 4.2.4 and the bf9b497 commit referenced by @sethk above. Any tips?

**Comment by sethk** [comment]
@dmexs, does your browser's console show the font load as 404'd, or is the @font-face for it present in the CSS at the top level?

**Comment by dmexs** [comment]
@sethk I see the at-root block with the includes in my application.css but I don't see any 404s in the browser.

**Comment by zxnn** [comment]
Make sure the font files is in the right places and the  @font-face is correct .
I found @at-root before @font-face in your css file, remove @at-root and it will be work.

**Comment by rocco** [comment]
@dmexs I had the same issue. Whenver at-root is still in your final CSS, your Sass compiler is outdated. I had to upgrade libsass to 3.2. See here: http://sass-compatibility.github.io/#at_root_directive

**Comment by dmexs** [comment]
@rocco thanks. upgraded to sass 3.4.18 and all is gravy.

**Comment by ivanbozic** [comment]
My solution was to update **sass-rails** to the following to get it to work.
```
sass-rails, '~> 5.0.4'
```

Also had to mess around with versions of some other gems because of conflicts, but the line above was what fixed it for me.

**Comment by andrewhavens** [comment]
Here's what I did to get it to work. Sounds similar to what others are mentioning:

### Gemfile:

```
# Before
gem 'sass-rails', '~> 4.0.2'
gem 'bootstrap-sass', '~> 3.3'

# After
gem 'sass-rails', '~> 5.0.1'
gem 'bootstrap-sass', '= 3.3.4.1' # I downgraded to this version
```

This resulted in:

### Gemfile.lock:
```
# Before
    bootstrap-sass (3.3.5)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)

# After
    bootstrap-sass (3.3.4.1)
    sass (3.4.18)
    sass-rails (5.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
```

**Comment by fleveque** [comment]
Same here,... Upgrading sass and sass-rails worked for me:

```
gem 'sass-rails', '>= 3.2'
```

bundle update --source sass-rails
bundle update --source sass

```
sass (3.4.18)
sass-rails (5.0.4)
```

**Comment by sethk** [comment]
Perhaps enough people are getting snagged on this that y'all should do another dot release?

**Comment by t6847kimo** [comment]
Hi I had same issue yesterday, but i fix after run bundle update sprockets-rails
For you guys reference :D
Here is my Gemfile:
gem 'rails', '4.0.2'
gem 'sass', '~> 3.4.18'
gem 'sass-rails', '~> 5.0.1'
gem 'bootstrap-sass', '~> 3.3.5' 

sprockets (2.12.4)
sprockets-rails (2.0.1)

**Comment by cvrebert** [comment]
I believe this was fixed in bootstrap-sass 3.3.6.

**Comment by parsaap** [comment]
I had the same issue. I changed the order of imports in application.css.scss and it got fixed. Originally it was:

@import "bootstrap";
@import "bootstrap-sprockets";

and it was trying to get the font from /fonts/glyphicons-halflings-regular.woff2. Then I changed it to:

@import "bootstrap-sprockets";
@import "bootstrap";

and now the font url is /assets/glyphicons-halflings-regular.woff2

**Comment by sethk** [comment]
@parsaap I've had that issue as well, but it's covered prominently in the `README`. It would be nice if missing the `@import "bootstrap-sprockets"` yielded a warning, but there are probably legitimate reasons not to do so.

**Comment by Thomacho** [comment]
I know this is not a new issue, but I've been struggling to solve it these last two days. I knew the issue was related to the '@at_root' directive not being processed but only this page put me on the right track. Unfortunately, comments above didn't solve the problem. For me, there was one more gem to update: Sprockets. I was using **sprockets 2.12.4** and I had to run a `bundle update --source sprockets` to upgrade to version **sprockets 3.7.1**
For other gems, I followed the comments above and in the end my problem was solved.
Thanks to all, for their input.

**Comment by alexanmtz** [comment]
```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url(asset_path('glyphicons-halflings-regular.eot'));
  src: url(asset_path('glyphicons-halflings-regular.eot?#iefix')) format('embedded-opentype'), url(asset_path('glyphicons-halflings-regular.woff')) format('woff'), url(asset_path('glyphicons-halflings-regular.ttf')) format('truetype'), url(asset_path('glyphicons-halflings-regular.svg#glyphicons_halflingsregular')) format('svg');
}
```
